apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: kredis-test
  name: {{ $.Release.Name }}-kredis-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kredis-test
    spec:
      containers:
      - name: kredis-test
        imagePullPolicy: IfNotPresent
        image: ereon/kredis-test
        args:
        {{ range $redisHost := $.Values.redisHosts }}
        - {{ $redisHost }}
        {{ end }}
